version: '3'

services:
  web:
    build: ./web
    ports:
      - "8000:8000"
    volumes:
      - ./web:/usr/src/app
      - ./web/media:/usr/src/app/media
      - ./web/static:/usr/src/app/static
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: .env

volumes:
  web:
