# Generated by Django 2.0.8 on 2018-09-04 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoDesafio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentário')),
                ('nota', models.IntegerField(verbose_name='Nota')),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='dataHora')),
            ],
        ),
        migrations.CreateModel(
            name='CasoDeTeste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada_do_desafio', models.TextField(blank=True, null=True, verbose_name='Entrada do desafio')),
                ('saida_do_desafio', models.TextField(blank=True, null=True, verbose_name='Saída do desafio')),
            ],
        ),
        migrations.CreateModel(
            name='Conquista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conquista', models.CharField(default='0', max_length=50, verbose_name='Nome da conquista')),
                ('usuario', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=256, verbose_name='Título do desafio')),
                ('tempo_de_resposta', models.TimeField(default='DEFAULT VALUE', help_text='O tempo limite para resolver o desafio', verbose_name='Tempo de resposta do desafio')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('enunciado', models.TextField(blank=True, null=True, verbose_name='Enunciado')),
                ('pre_codigo', models.TextField(blank=True, null=True, verbose_name='Pré-código')),
                ('estah_publicado', models.BooleanField(default='0')),
                ('data_de_cadastro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Cadastro')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoDesafio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desafio_vencido', models.IntegerField(default='0', verbose_name='Desafio vencido')),
            ],
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=255, verbose_name='endereco')),
                ('descricao', models.CharField(max_length=200, verbose_name='descricao')),
            ],
            options={
                'verbose_name': 'Imagem',
                'verbose_name_plural': 'Imagens',
            },
        ),
        migrations.CreateModel(
            name='NivelDeDificuldade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(verbose_name='Nível de dificuldade')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_do_desafio', models.TextField(blank=True, null=True, verbose_name='Resposta do desafio')),
                ('data_da_resposta', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Resposta')),
                ('desafio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambiente_codelive.Desafio')),
                ('usuario', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RespostaTreino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.TextField(blank=True, null=True, verbose_name='Resposta do treino')),
                ('data_da_resposta', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da respota')),
                ('desafio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambiente_codelive.Desafio')),
                ('usuario', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_das_tags', models.TextField(blank=True, null=True, verbose_name='Nome da tag')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.AddField(
            model_name='historicodesafio',
            name='resposta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambiente_codelive.Resposta'),
        ),
        migrations.AddField(
            model_name='desafio',
            name='nivel_de_dificuldade',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='ambiente_codelive.NivelDeDificuldade'),
        ),
        migrations.AddField(
            model_name='desafio',
            name='tags',
            field=models.ManyToManyField(to='ambiente_codelive.Tag', verbose_name='Lista das tags'),
        ),
        migrations.AddField(
            model_name='casodeteste',
            name='desafio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambiente_codelive.Desafio'),
        ),
        migrations.AddField(
            model_name='avaliacaodesafio',
            name='desafio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambiente_codelive.Desafio'),
        ),
        migrations.AddField(
            model_name='avaliacaodesafio',
            name='usuario',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
