# Generated by Django 2.0.8 on 2018-09-05 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente_codelive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desafio',
            name='nivel_de_dificuldade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambiente_codelive.NivelDeDificuldade'),
        ),
    ]
