# Generated by Django 2.0.8 on 2018-09-25 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ambiente_codelive', '0002_auto_20180904_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(upload_to='')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='avaliacaodesafio',
            name='desafio',
        ),
        migrations.RemoveField(
            model_name='avaliacaodesafio',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='conquista',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Imagem',
        ),
        migrations.RemoveField(
            model_name='respostatreino',
            name='desafio',
        ),
        migrations.RemoveField(
            model_name='respostatreino',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='casodeteste',
            name='entrada_do_desafio',
        ),
        migrations.RemoveField(
            model_name='casodeteste',
            name='saida_do_desafio',
        ),
        migrations.RemoveField(
            model_name='historicodesafio',
            name='desafio_vencido',
        ),
        migrations.AddField(
            model_name='casodeteste',
            name='entrada',
            field=models.TextField(blank=True, null=True, verbose_name='Entrada'),
        ),
        migrations.AddField(
            model_name='casodeteste',
            name='saida',
            field=models.TextField(blank=True, null=True, verbose_name='Saída'),
        ),
        migrations.AddField(
            model_name='historicodesafio',
            name='historico_do_desafio',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='AvaliacaoDesafio',
        ),
        migrations.DeleteModel(
            name='Conquista',
        ),
        migrations.DeleteModel(
            name='RespostaTreino',
        ),
    ]
