# Generated by Django 2.0.8 on 2018-09-25 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente_codelive', '0003_auto_20180925_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desafio',
            options={'permissions': (('ver_desafio', 'Pode ver desafio'), ('dirigir_moto', 'Pode dirigir moto'))},
        ),
    ]
