# Generated by Django 2.0.8 on 2018-10-03 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente_codelive', '0004_auto_20180925_2038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desafio',
            options={},
        ),
    ]
