# Generated by Django 2.1.2 on 2018-10-22 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente_codelive', '0007_desafio_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrecaoAutomaticaDeResposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('pontuacao', models.FloatField(default=0.0, verbose_name='Pontuação')),
                ('total_cpu', models.FloatField(blank=True, null=True, verbose_name='Uso de CPU (%)')),
                ('total_memoria_kb', models.FloatField(blank=True, null=True, verbose_name='Uso de RAM (%)')),
                ('total_runtime', models.FloatField(blank=True, null=True, verbose_name='Tempo de execução (ms)')),
                ('resposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correcoes', to='ambiente_codelive.Resposta')),
            ],
            options={
                'verbose_name': 'Correção Automática de Resposta',
                'verbose_name_plural': 'Correções automáticas de respostas',
            },
        ),
        migrations.CreateModel(
            name='ResultadoDeCasoDeTesteDeCorrecaoAutomatica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('pontuacao', models.FloatField(default=0.0, verbose_name='Pontuação')),
                ('total_cpu', models.FloatField(blank=True, null=True, verbose_name='Uso de CPU (%)')),
                ('total_memoria_kb', models.FloatField(blank=True, null=True, verbose_name='Uso de RAM (%)')),
                ('total_runtime', models.FloatField(blank=True, null=True, verbose_name='Tempo de execução (ms)')),
                ('saida_padrao', models.TextField(blank=True, null=True, verbose_name='Saída padrão')),
                ('saida_erro', models.TextField(blank=True, null=True, verbose_name='Saida erro')),
                ('correcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_casos_de_teste', to='ambiente_codelive.CorrecaoAutomaticaDeResposta')),
            ],
            options={
                'verbose_name': 'Resultado de caso de teste de correção automática',
                'verbose_name_plural': 'Resultados de casos de teste de correções automáticas',
            },
        ),
        migrations.AlterModelOptions(
            name='casodeteste',
            options={'verbose_name': 'Caso de Teste', 'verbose_name_plural': 'Casos de Teste'},
        ),
        migrations.AlterModelOptions(
            name='niveldedificuldade',
            options={'verbose_name': 'Nível de dificuldade', 'verbose_name_plural': 'Níveis de Dificuldade'},
        ),
    ]
