# Generated by Django 2.1.2 on 2018-11-02 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente_codelive', '0008_auto_20181022_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyDesafio',
            fields=[
            ],
            options={
                'verbose_name': 'Meu Desafio',
                'verbose_name_plural': 'Meus Desafios',
                'proxy': True,
                'indexes': [],
            },
            bases=('ambiente_codelive.desafio',),
        ),
        migrations.CreateModel(
            name='ProxyDesafioProfessor',
            fields=[
            ],
            options={
                'verbose_name': 'Desafio Professor',
                'verbose_name_plural': 'Desafios do Professor',
                'proxy': True,
                'indexes': [],
            },
            bases=('ambiente_codelive.desafio',),
        ),
        migrations.CreateModel(
            name='ProxyPerfil',
            fields=[
            ],
            options={
                'verbose_name': 'Meu Perfil',
                'verbose_name_plural': 'Meus Perfis',
                'proxy': True,
                'indexes': [],
            },
            bases=('ambiente_codelive.perfil',),
        ),
        migrations.CreateModel(
            name='ProxyResposta',
            fields=[
            ],
            options={
                'verbose_name': 'Minha resposta',
                'verbose_name_plural': 'Minhas respostas',
                'proxy': True,
                'indexes': [],
            },
            bases=('ambiente_codelive.resposta',),
        ),
        migrations.CreateModel(
            name='ProxyRespostaProfessor',
            fields=[
            ],
            options={
                'verbose_name': 'Resposta do Professor',
                'verbose_name_plural': 'Responder os Desafios do Professor',
                'proxy': True,
                'indexes': [],
            },
            bases=('ambiente_codelive.resposta',),
        ),
        migrations.AlterModelOptions(
            name='desafio',
            options={'verbose_name': 'Desafio', 'verbose_name_plural': 'Desafios'},
        ),
        migrations.AlterModelOptions(
            name='resposta',
            options={'verbose_name': 'Resposta', 'verbose_name_plural': 'Respostas'},
        ),
        migrations.AlterField(
            model_name='correcaoautomaticaderesposta',
            name='total_memoria_kb',
            field=models.FloatField(blank=True, null=True, verbose_name='Uso de RAM (KB)'),
        ),
        migrations.AlterField(
            model_name='resultadodecasodetestedecorrecaoautomatica',
            name='total_memoria_kb',
            field=models.FloatField(blank=True, null=True, verbose_name='Uso de RAM (KB)'),
        ),
    ]
