# Generated by Django 2.1.2 on 2018-11-02 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente_codelive', '0009_auto_20181101_2320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proxydesafioprofessor',
            options={'verbose_name': 'Desafio Cadastrado', 'verbose_name_plural': 'Desafios Cadastrados'},
        ),
    ]
