# Generated by Django 2.1.2 on 2018-11-05 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente_codelive', '0010_auto_20181101_2347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desafio',
            options={'verbose_name': 'Modificar Desafio Cadastrado', 'verbose_name_plural': 'Modificar Desafios Cadastrados'},
        ),
        migrations.AlterField(
            model_name='resposta',
            name='data_da_resposta',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da Resposta'),
        ),
    ]
