# Generated by Django 2.1.2 on 2018-11-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente_codelive', '0012_remove_desafio_tempo_de_resposta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desafio',
            options={'verbose_name': 'Desafio', 'verbose_name_plural': 'Desafios'},
        ),
        migrations.AddField(
            model_name='desafio',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='desafio',
            name='data_de_cadastro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro'),
        ),
    ]
